In [4]:
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size=8
batch_size=4

cuda


In [5]:
with open('wizard_of_oz.txt','r', encoding='utf-8') as f:
    text=f.read()
chars = sorted(set(text))
print(chars)
print(len(chars))

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
81


In [6]:
string_to_int={ch:i for i, ch in enumerate(chars) }
int_to_string = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


In [10]:
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[n:]

def get_batch(split):
    data=train_data if split =='train' else val_data
    ix=torch.randint(len(data) -block_size, (batch_size,))
    print(ix)
    x=torch.stack([data[i:i+block_size] for i in ix])
    y=torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y=x.to(device), y.to(device)
    return x, y

x, y=get_batch('train')
print('inputs:')
#print(x.shape)
print(x)
print('targets:')
print(y)

tensor([ 20838, 113430, 100404,    542])
inputs:
tensor([[68, 68, 59,  1, 72, 68,  1, 73],
        [ 3, 54, 71, 58,  1, 66, 54, 67],
        [71, 72, 58,  1, 68, 59,  1, 54],
        [64, 67, 68, 76,  1, 65, 68, 73]], device='cuda:0')
targets:
tensor([[68, 59,  1, 72, 68,  1, 73, 61],
        [54, 71, 58,  1, 66, 54, 67, 78],
        [72, 58,  1, 68, 59,  1, 54,  1],
        [67, 68, 76,  1, 65, 68, 73, 72]], device='cuda:0')


In [14]:


x=train_data[:block_size]
y=train_data[1:block_size+1]

for t in range(block_size):
    context=x[:t+1]
    target= y[t]
    print('when the input is', context, 'target is', target)

when the input is tensor([80]) target is tensor(1)
when the input is tensor([80,  1]) target is tensor(1)
when the input is tensor([80,  1,  1]) target is tensor(28)
when the input is tensor([80,  1,  1, 28]) target is tensor(39)
when the input is tensor([80,  1,  1, 28, 39]) target is tensor(42)
when the input is tensor([80,  1,  1, 28, 39, 42]) target is tensor(39)
when the input is tensor([80,  1,  1, 28, 39, 42, 39]) target is tensor(44)
when the input is tensor([80,  1,  1, 28, 39, 42, 39, 44]) target is tensor(32)
